# Generated by Django 5.0.6 on 2024-06-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('Contact', models.IntegerField()),
                ('Mail', models.CharField(max_length=20)),
            ],
        ),
    ]
